### PR TITLE
Uploaded Helper Scripts

### PR DESCRIPTION
**Pull request by psyferlab**
These three files comprise the two-step installation process, with init.sh installing all necessary deps and the py script deals with key gen and insertion.

### CODE REVIEW

**Comment by psyferlab** [comment]
Reviewed.

**Review by pavondunbar — APPROVED** [review]
Works as planned. Approved by Pavon Dunbar

**Review by pavondunbar — APPROVED** [review]

**Review by pavondunbar — APPROVED** [review]
Works as planned. Approved by Pavon Dunbar

**Review by psyferlab — COMMENTED** [review]
Thank you.

**Pull request merged**
